engines:
  radon:
    enabled: true
  pep8:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python

ratings:
  paths:
  - src/**

exclude_paths:
- tests/**/*
- notebooks/**/*
- venv/**/*
- "**/vendor/**/*"
