checks:
    python:
        code_rating: true
        duplicate_code: true

tools:
    pylint:
        python_version: 2

filter:
    excluded_paths:
        - '*/test/*'
        - '*.min.js'
        - 'venv/*'
        - 'HTML_copies/*'
        - 'tests/*'
