sudo: false
language: python
cache: pip
python:
  - 2.7

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - pip install setuptools==25.2.0

install:
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
  - pip install coveralls

script:
  - python get_sic.py
  - py.test --cov=scrape_sic tests/
  - flake8 --statistics --show-source --disable-noqa scrape_sic

after_success:
  - coveralls
