sudo: false
language: python
cache: pip
python:
  - 2.7

# command to install dependencies
install:
  - pip install -r requirements.txt --download-cache $HOME/.pip-cache
  - pip install coveralls

# command to run tests
script:
  - py.test --cov=scrape_sic tests/
  - flake8 --statistics --show-source --disable-noqa scrape_sic

after_success:
  - coveralls
