sudo: false
language: python
cache: pip
python:
  - 2.7

# command to install dependencies
install:
  - pip install flake8
  - pip install coveralls
  - pip install -r requirements.txt

# command to run tests
script:
  - flake8 --statistics --show-source --disable-noqa scrape_sic
  - coverage run scrape_sic/scrape_sic_sec.py test
  - nosetests

after_success:
  - coveralls
